version: 2.1
jobs:
  build:
    docker:
      - image: node:19
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm run test:coveralls
