version: 2.1
jobs:
  build:
    docker:
      - image: node:10.23.0-buster
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Run Tests
          command: yarn test:coveralls
